import { useLocalSearchParams, useRouter } from 'expo-router';
import { useEffect, useState } from 'react';
import { Alert, Image, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import * as Location from 'expo-location';
import { api } from '@/src/lib/api';
import { LocalDraft, saveDraft } from '@/src/lib/drafts';
import { CameraCapture } from '@/src/components/CameraCapture';
import { persistCapturedPhoto, uploadCapturedPhoto } from '@/src/lib/media';
type Category = { id: string; name: string };
const clientDraftId = () => `draft-${Date.now()}-${Math.random().toString(36).slice(2, 12)}`;
export default function NewReport() {
  const router = useRouter(); const params = useLocalSearchParams<{categories:string}>(); const categories = JSON.parse(params.categories || '[]') as Category[];
  const [categoryId, setCategoryId] = useState(categories[0]?.id ?? ''); const [description, setDescription] = useState(''); const [coords, setCoords] = useState<{latitude:number;longitude:number}>(); const [locationMessage, setLocationMessage] = useState('Getting your current location…'); const [photoUri, setPhotoUri] = useState<string>(); const [saving, setSaving] = useState(false); const [saveMessage, setSaveMessage] = useState(''); const [debugLog, setDebugLog] = useState<string[]>(['Screen ready']);
  const trace = (message: string) => { const line = `${new Date().toLocaleTimeString()} ${message}`; console.log(`[demo-report] ${line}`); setDebugLog((items) => [line, ...items].slice(0, 8)); };
  const locate = async () => { trace('GPS request started'); setLocationMessage('Getting your current location…'); const permission = await Location.requestForegroundPermissionsAsync(); if (permission.status !== 'granted') { trace('GPS permission denied'); setLocationMessage('Location permission is required to submit a report.'); return; } try { const current = await Location.getCurrentPositionAsync({ accuracy: Location.Accuracy.Balanced }); setCoords(current.coords); trace('GPS captured'); setLocationMessage('Current location captured. CivicPulse will round public locations for privacy.'); } catch (error) { trace(`GPS failed: ${error instanceof Error ? error.message : 'unknown error'}`); setLocationMessage('Could not get your location. Move outdoors and refresh GPS.'); } };
  useEffect(() => { void locate(); }, []);
  const local = (): LocalDraft => ({ id: clientDraftId(), categoryId, categoryName: categories.find((category) => category.id === categoryId)?.name ?? 'Civic issue', description, visibility: 'PRIVATE', photoUri, ...coords, state:'LOCAL', createdAt:new Date().toISOString() });
  const submit = async () => { trace(`Save pressed: category=${Boolean(categoryId)}, photo=${Boolean(photoUri)}, gps=${Boolean(coords)}, description=${description.trim().length}`); if (!categoryId || description.trim().length < 10 || !coords || !photoUri) { trace('Save blocked by validation'); return Alert.alert('Complete the report', 'Take a photo, add at least 10 characters, and allow CivicPulse to capture your current location.'); } let draft = local(); setSaving(true); setSaveMessage('Saving report…'); try { if (process.env.EXPO_PUBLIC_DEMO_MODE === 'true') { trace('Persisting photo locally'); const persistedPhoto = await persistCapturedPhoto(photoUri); trace('Photo persisted locally'); draft = { ...draft, photoUri: persistedPhoto }; saveDraft(draft); trace('Draft written to SQLite'); setSaveMessage('Saved on this device.'); Alert.alert('Saved on this device', 'Your demo report is saved locally. Use Sync now from the dashboard when you want to send it to the local API.'); trace('Navigating to dashboard'); router.replace('/'); return; } trace('Creating remote report'); const report = await api<{id:string}>('/reports', { method:'POST', headers:{'Idempotency-Key':draft.id}, body:JSON.stringify({categoryId,description,visibility:'PRIVATE',locationSource:'GPS',...coords}) }); setSaveMessage('Saving captured photo…'); trace('Uploading photo'); await uploadCapturedPhoto(report.id, photoUri); trace('Remote save completed'); Alert.alert('Saved', 'Your report and captured photo are saved.'); router.replace(`/report/${report.id}`); } catch (error) { trace(`Save failed: ${error instanceof Error ? error.message : 'unknown error'}`); saveDraft(draft); trace('Fallback draft written to SQLite'); setSaveMessage('Saved on this device.'); Alert.alert('Saved on this device', error instanceof Error ? error.message : 'We will sync this report when you are back online.'); router.replace('/'); } finally { setSaving(false); } };
  return <ScrollView contentContainerStyle={styles.container}><Text style={styles.note}>CivicPulse does not submit complaints to government systems. It helps you document and track them.</Text><Text style={styles.label}>Issue type</Text><View style={styles.row}>{categories.map((c)=><Pressable key={c.id} onPress={()=>setCategoryId(c.id)} style={[styles.chip,categoryId===c.id&&styles.selected]}><Text>{c.name}</Text></Pressable>)}</View><Text style={styles.label}>Issue photo</Text>{photoUri ? <><Image source={{uri:photoUri}} style={styles.preview}/><CameraCapture onCapture={(uri) => { trace('Camera photo attached'); setPhotoUri(uri); }}/><Text style={styles.note}>Photo attached. Take another photo to replace it.</Text></> : <><CameraCapture onCapture={(uri) => { trace('Camera photo attached'); setPhotoUri(uri); }}/><Text style={styles.note}>Camera capture is required. Gallery selection is not available.</Text></>}<Text style={styles.label}>What happened?</Text><TextInput multiline style={[styles.input,{height:120}]} value={description} onChangeText={setDescription} placeholder="Describe the issue and nearby landmark."/><Text style={styles.label}>Current location</Text><Text style={styles.note}>{locationMessage}</Text><Pressable style={styles.secondary} onPress={() => void locate()}><Text>Refresh GPS location</Text></Pressable>{saveMessage ? <Text style={styles.note}>{saveMessage}</Text> : null}<Pressable disabled={saving} style={[styles.button,saving&&styles.buttonDisabled]} onPress={submit}><Text style={styles.buttonText}>{saving?'Saving…':'Save report'}</Text></Pressable><View style={styles.debug}><Text style={styles.debugTitle}>Demo debug log</Text>{debugLog.map((line,index)=><Text key={`${line}-${index}`} style={styles.debugText}>{line}</Text>)}</View></ScrollView>;
}
const styles=StyleSheet.create({container:{padding:20,gap:11},note:{color:'#43565c',lineHeight:20},label:{fontWeight:'700',marginTop:5},input:{backgroundColor:'#fff',borderWidth:1,borderColor:'#cbd5d8',borderRadius:10,padding:12,textAlignVertical:'top'},row:{flexDirection:'row',gap:8,flexWrap:'wrap'},chip:{borderWidth:1,borderColor:'#9caeb2',borderRadius:20,padding:10,backgroundColor:'#fff'},selected:{backgroundColor:'#cce9e6',borderColor:'#0b6e69'},preview:{width:'100%',height:220,borderRadius:12,backgroundColor:'#dde'},secondary:{alignSelf:'flex-start',padding:10},button:{backgroundColor:'#0b6e69',padding:16,borderRadius:10,alignItems:'center',marginTop:14},buttonDisabled:{opacity:.6},buttonText:{color:'#fff',fontWeight:'700'},debug:{backgroundColor:'#152225',borderRadius:8,padding:10,marginTop:12,gap:3},debugTitle:{color:'#a7f3d0',fontWeight:'700'},debugText:{color:'#e5e7eb',fontFamily:'monospace',fontSize:11}});
